server:
  port: 15000

spring:
  application:
    name: KostaErpServer
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kind: Application
logging:
  level:
    com.oopsw: info

mybatis:
  #  type-aliases-package: com.oopsw.aspringweb.dao
  type-aliases-package: com.oopsw.kostaerpserver.vo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true